version: '3.8'
services:
  postgres:
    container_name: postgres
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ms
    ports:
      - '5432:5432'
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
  configuration:
    container_name: configuration
    image: turkuazsengul/ms-node-configuration
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"
    ports:
      - "8888:8888"
  discovery:
    container_name: eureka
    image: turkuazsengul/ms-node-discovery
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"
    ports:
      - "5555:5555"