server:
  port: 8282
  error:
    include-binding-errors: always
    include-message: always
spring:
  application:
    name: servis-qa-automation
  config:
#    import: configserver:http://configuration:8888
    import: configserver:http://localhost:8888