server:
  port: ${app.port:20000}
  error:
    include-binding-errors: always
    include-message: always
spring:
  application:
    name: product
  config:
    import: configserver:http://configuration:8888
#app:
#  domain: d1
#  subdomain: sb1
#  boundedcontext: b1
#  microservice: ${spring.application.name}