server:
  port: 5555
eureka:
  client:
    service-url:
      defaultZone: http://localhost:5555/eureka/
    register-with-eureka: true
    fetch-registry: true
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true
  server:
    enable-self-preservation: false
#ssda
#server.port=5555
#
#eureka.client.service-url.defaultZone=http://127.0.0.1:5555/eureka/
#eureka.client.register-with-eureka=false
#eureka.client.fetch-registry=false
#eureka.client.healthcheck.enabled=false
#eureka.instance.prefer-ip-address=true
#
#eureka.server.enable-self-preservation=false
